// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID          int32
	Email       string
	Username    string
	Password    string
	IsBlock     bool
	Ua          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	AccessToken sql.NullString
	ProxyID     sql.NullInt32
}

type Proxy struct {
	ID        int32
	Ip        string
	Port      string
	Username  string
	Password  string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
